export const playersList = [
    {
        id: "player-orange-1",
        firstName: "One",
        lastName: "Orange",
        height: "187",
        weight: "82",
        games: [],
        titles: [],
        number: "1",
        team: "team-orange",
    },
    {
        id: "player-orange-2",
        firstName: "Two",
        lastName: "Orange",
        height: "187",
        weight: "82",
        games: [],
        titles: [],
        number: "2",
        team: "team-orange",
    },
    {
        id: "player-blue-1",
        firstName: "One",
        lastName: "Blue",
        height: "187",
        weight: "82",
        games: [],
        titles: [],
        number: "1",
        team: "team-blue",
    },
    {
        id: "player-blue-2",
        firstName: "Two",
        lastName: "Blue",
        height: "187",
        weight: "82",
        games: [],
        titles: [],
        number: "2",
        team: "team-blue",
    },
    {
        id: "player-green-1",
        firstName: "One",
        lastName: "Green",
        height: "187",
        weight: "82",
        games: [],
        titles: [],
        number: "1",
        team: "team-green",
    },
    {
        id: "player-green-2",
        firstName: "Two",
        lastName: "Green",
        height: "187",
        weight: "82",
        games: [],
        titles: [],
        number: "2",
        team: "team-green",
    },
];
